name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v4
        with:
          name: Mini.OutfitExporter.dll
          path: Mini.OutfitExporter/bin/Release/net6.0/Mini.OutfitExporter.dll
